name: Build & Test

on: [push]

jobs:
  spm:
    name: "With SPM"
    runs-on: windows-2022
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup-swift

    - name: Build
      shell: pwsh
      run: swift build --verbose --build-tests

    - name: Test
      shell: pwsh
      run: swift test --verbose --skip-build

  cmake:
    name: With CMake (No Tests)
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup-swift

    - name: CMake Configure
      shell: pwsh
      run: cmake --preset debug

    - name: CMake Build
      shell: pwsh
      run: cmake --build --preset debug