name: Build & Test

on: [push]

jobs:
  build-and-test-spm:
    name: "Build and Test (SPM)"
    runs-on: windows-2022
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Setup Visual Studio Development Environment
      uses: compnerd/gha-setup-vsdevenv@main

    - name: Install Swift
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-5.8-release
        tag: 5.8-RELEASE

    - name: Build
      shell: pwsh
      run: swift build --verbose --build-tests

    - name: Test
      shell: pwsh
      run: swift test --verbose --skip-build

  build-cmake:
    name: Build (CMake)
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-swift

    - name: CMake Configure
      shell: pwsh
      run: cmake --preset debug

    - name: CMake Build
      shell: pwsh
      run: cmake --build --preset debug